version: '3.3'

services:
  app1:
    image: hello
    container_name: app1
    ports:
      - "8000:80"
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  app2:
    image: hello
    container_name: app2
    ports:
      - "8001:80"
    networks:
      app_net:
        ipv4_address: 172.16.238.11

  app3:
    image: hello
    container_name: app3
    ports:
      - "8002:80"
    networks:
      app_net:
        ipv4_address: 172.16.238.12

#  ha1:
#    image: haproxy
#    container_name: haproxy
#    ports:
#      - "8080:80"
#      - "1984:1984"
#    volumes:
#      - type: bind
#        source: ./ha/haproxy.cfg
#        target: /usr/local/etc/haproxy/haproxy.cfg
#
#    networks:
#      app_net:
#        ipv4_address: 172.16.238.13

  keepalived_haproxy_matser:
    image: goldenroute/keepalived-haproxy:latest
    container_name: keepalived_haproxy_matser
    command: [-f, /usr/local/etc/haproxy/haproxy.cfg]
    privileged: true
    volumes:
      - type: bind
        source: ./ha/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg

      - ./ha/docker-keepalived-haproxy/keepalived:/keepalived

    environment:
#        INTERFACE: "enp0s3"
        STATE: "MASTER"
        VIRTUAL_ROUTER_ID: "51"
        PRIORITY: "101"
        VIRTUAL_IP: "172.168.238.13"
        VIRTUAL_MASK: "24"

    networks:
      app_net:
        ipv4_address: 172.16.238.14




  keepalived_haproxy_backup:
    image: goldenroute/keepalived-haproxy:latest
    container_name: keepalived_haproxy_backup
    command: [-f, /usr/local/etc/haproxy/haproxy.cfg]
    privileged: true
    volumes:
      - type: bind
        source: ./ha/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg

      - ./ha/docker-keepalived-haproxy/keepalived:/keepalived


    environment:
#        INTERFACE: "enp0s3"
        STATE: "BACKUP"
        VIRTUAL_ROUTER_ID: "51"
        PRIORITY: "100"
        VIRTUAL_IP: "172.168.238.13"
        VIRTUAL_MASK: "24"

    networks:
      app_net:
        ipv4_address: 172.16.238.15

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
