---
- hosts: docker
  sudo: True
  gather_facts: False
  tasks:
    - name: Install required packages
      yum: name={{ item }} state=present
      with_items:
       - yum-utils
       - device-mapper-persistent-data
       - lvm2

    - name: Set up the stable repository
      command: yum-config-manager --add-repo {{ docker_stable_repository }}

    - name: Install Docker CE
      yum: name=docker-ce  state=present

    - name: Start docker and configure it to run at boot.
      service:
        name: docker
        state: started
        enabled: yes

    - name: Download the latest version of Docker Compose
      get_url:
        url: "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose

    - name: Apply executable permissions to the binary
      command: chmod +x /usr/local/bin/docker-compose